### ISSUE TITLE
Entry point support

### ISSUE THREAD

**Issue by tomusdrw** [FluffyLabs/pvm-debugger#105]
Currently all our programs have just one entry point. We assume that the Program Counter should be set to `0` and start off from there.

However, JAM programs will have multiple entry points:
<img width="479" alt="image" src="https://github.com/user-attachments/assets/5db2e300-155d-4398-90c2-408b2a2e0c0d">

> To give more background on this: the way this will work in practice is that the program will have 4 unconditional jump instructions at the very start, and the first 3 of those instructions will be encoded in such a way as to be padded and always take up 5 bytes of space. Hence the entry points of 0, 5, 10 and 15. This design allows for hardcoded addresses for each of the entry points without having to specify them dynamically anywhere in the protocol.

**Comment by wkwiatek** [comment]
Fixed with: https://github.com/FluffyLabs/pvm-debugger/pull/108
