### ISSUE TITLE
Discrepancy between execution a program on pvm and polkavm

### ISSUE THREAD

**Issue by mateuszsikora** [FluffyLabs/pvm-debugger#113]
let's execute the add instruction example:
- in case of PVM we need 2 steps to execute the program 
- in case of PolkaVM we need 3 steps to execute the program

**Comment by tomusdrw** [comment]
I initially thought this might be an issue with polkavm, but I've pushed a new version, where the `nextStep` is called right upon reset:
https://github.com/tomusdrw/polkavm/commit/4d60e85534bcaf043a9663faf8355d6635685c72

This now works correctly as verified by this test:
https://github.com/tomusdrw/polkavm/commit/5d56be9bd9b1f1f35d79c7c46d7da166372f6afc

However in the PVM debugger (`main` branch) I still see that the PC is one step behind. I think that it might be something with the polkavm initialisation in the debugger. @wkwiatek let me know if you need any more info on this one.

I've requested #130 to make sure I'm running the correct one, I guess it's also possible that the `wasm` is cached in the browser, but I've checked a fresh instance (firefox) and it was still nok.

**Comment by wkwiatek** [comment]
Related PR fixes the issue by adhering to the latest API: https://github.com/FluffyLabs/pvm-debugger/pull/134. 

However, there is a gas difference still. This is coming from PVMs themselves. 

Would it be possible for you to look at it?

**Comment by wkwiatek** [comment]
OK! So we just need to ensure we have smooth run functionality experience but that's another story
