### ISSUE TITLE
Multiple PVM view fixes

### ISSUE THREAD

**Issue by piotrzwolinski** [FluffyLabs/pvm-debugger#127]
- [ ] Separator line for loading options
![image](https://github.com/user-attachments/assets/c2b04300-0439-4ca2-9836-54779bc9a224)

- [ ] Min one PVM must be always selected (cannot deselect last one)
![image](https://github.com/user-attachments/assets/9265eabc-3e8b-44b3-8403-c38b110c7e8a)

- [ ] Loading functions should not be checkboxes
![image](https://github.com/user-attachments/assets/9265eabc-3e8b-44b3-8403-c38b110c7e8a)

- [ ] shorten texts to "Uploaded PVM", "PVM from URL"

- [ ] upload from URL -> name from metadata
- [ ] upload from file -> user can enter the name (initially populate with filename)

**Comment by tomusdrw** [comment]
I'd also suggest shortening the labels after the PVMs are selected. It should be just "Uploaded PVM", "PVM from URL"
