### ISSUE TITLE
Clicking 'reset' displays an error

### ISSUE THREAD

**Issue by tomusdrw** [FluffyLabs/pvm-debugger#149]
Yet seamingly everything works fine.

**Comment by wkwiatek** [comment]
@tomusdrw it seems like this is only the issue for PolkaVM - could you confirm? 

Also the real reason can be now seen in the console:
<img width="614" alt="image" src="https://github.com/user-attachments/assets/0981c016-984f-47a6-83aa-6a0a1cef23c8">

So it looks like there's no there anymore. I guess it was there but it could be just the case for typeberry. 

Can you confirm?

**Comment by tomusdrw** [comment]
Yeah, I think it was fixed by #162
