### ISSUE TITLE
Remove the initial state

### ISSUE THREAD

**Issue by tomusdrw** [FluffyLabs/pvm-debugger#150]
The initial state (before loading the program) should not be displayed at all. Ideally all 3 sections (program, status, memory) should be collapsed into one and inside that whitespace we should just display the dialog that's accessible after clicking 'Load' (i.e. all of the options of loading the programs).

![image](https://github.com/user-attachments/assets/d4616969-d442-4b9a-a068-d4278cf570d0)

**Comment by krystian50** [comment]
@tomusdrw if we show the dialog instead the whole current UI, should it be clossable? What if you close the dialog? Maybe we should show the dialog's content instead centered on the page?

**Comment by tomusdrw** [comment]
Yes, sorry I've mistyped, it should be the dialog content being shown at that merged area, not the dialog window.

Selecting PVM should stay as-is - it's fine (it's apart from the central real estate). It's just we shouldn't display any state of the PVM if the program is not loaded.

**Comment by wkwiatek** [comment]
Closed by #157 I guess
