### ISSUE TITLE
Memory cells should not wrap

### ISSUE THREAD

**Issue by tomusdrw** [FluffyLabs/pvm-debugger#154]
The memory cells should not wrap to a new line. Instead an x-scroll should be displayed if they don't fit in the space. Additionally the gap between cells should be lowered. In case of DEC it should be just slightly bigger than the gap between numbers or it can be the same but we should slightly alternate the colors between even and odd cells. For HEX there should be no gap at all, alternating the color on top (only slightly) is also fine.

![image](https://github.com/user-attachments/assets/b714e556-85a0-4aa7-bc0e-0523d6417cb2)

**Comment by krystian50** [comment]
PR: https://github.com/FluffyLabs/pvm-debugger/pull/157

**Comment by tomusdrw** [comment]
@krystian50 sorry for changing this again, but I think we need to have some better logic for address<>bytes alignment, cause it doesn't look good for large addresses:
<img width="323" alt="image" src="https://github.com/user-attachments/assets/43684378-1bde-4812-86f9-d965a9d34c59">
