### ISSUE TITLE
Errors while loading Service file.

### ISSUE THREAD

**Issue by tomusdrw** [FluffyLabs/pvm-debugger#159]
@mateuszsikora seems to complain about sbrk and heap stuff in console.
[test (1).json](https://github.com/user-attachments/files/17558096/test.1.json)

That said - if there are critical errors from the PVM I should not be able to step through the execution. Now I can do that (and it works for the first time).
After I reset it still works, but somehow "Step" jumps directly from `PC=5` to `PC=31` and HALTs immediately.

**Comment by wkwiatek** [comment]
@tomusdrw  How would you differentiate critical errors vs lower prio ones? 

I get your point but on the other hand it just allows you to play with the PVM and see how it behaves so in my opinion it's not bad. Ofc until it fails to show the truth. 

Technically I can think of a solution like: if anything goes wrong during the init then lock the UI, but then it would be require to have perfectly prepared PVM. It would be cumbersome if let's say something crashes but may not matter that much during the development for a given case under testing.

**Comment by tomusdrw** [comment]
1. We should assume that PVM is perfectly prepared, any (unexpected) error coming from calling any of the PVM functions should result in the UI refusing to do any other action with that PVM instance, because what the user sees will be garbage.
2. I'd like to propose to introduce a special "STATUS = Error" and display that in the UI (it should be treated the same as `PANIC`). We can display some extra error info in the tooltip (the entire exception dump even).

Any errors coming from non-PVM can be treated as non-critical and displayed as toasts.

**Comment by tomusdrw** [comment]
PVM:
1. We should assume that PVM is perfectly prepared, any (unexpected) error coming from calling any of the PVM functions should result in the UI refusing to do any other action with that PVM instance, because what the user sees will be garbage.
2. I'd like to propose to introduce a special "STATUS = Error" and display that in the UI (it should be treated the same as `PANIC`). We can display some extra error info in the tooltip (the entire exception dump even). So basically when the worker has an exception, every time we ask for status from now on it will return this error status and we will render that in the UI.

Program loading:
1. Any error during disassemblify of program (or loading JSON file) should also be treated as critical - i.e. we don't display the program but rather display an error.
2. It's fine to just revert to the initial screen (where no program is loaded) and display a toast (but be careful with #156)

Others:
1 Any errors coming from non-PVM non-program init can be treated as non-critical and displayed as toasts.

**Comment by krystian50** [comment]
Should be relatively simple with the new approach for catching errors. I'll take a look during weekend

**Comment by krystian50** [comment]
This issue should stay open for a bit longer. The test file sent here now fails at a different step. Blocking UI from the execution is a separate code to be written.

**Comment by krystian50** [comment]
Alright, I added error handling, but I cannot find any program to actually break PVM on step or run. This error is mocked by throwing error in PVM on nextStep():
<img width="1556" alt="image" src="https://github.com/user-attachments/assets/03a6b00d-fdb4-44ad-975e-cdf4686a61b9">
