### ISSUE TITLE
Memory page input box validation

### ISSUE THREAD

**Issue by tomusdrw** [FluffyLabs/pvm-debugger#172]
Since the memory page is filled at start now (#157) and given that #135 is `prio-low` the component should now have some validation.

1. Negative numbers should not be allowed or should cause the component to be in error status (explained below)
2. When the input is empty (after you backspace the initial "0" for instance) the component should be in error status.
3. Writing a too large number should also be indicated with error status (there is now error in the console, the UI does not refresh, but there is no toast). 
<img width="594" alt="image" src="https://github.com/user-attachments/assets/d32441c4-b568-4129-80ca-74b91e7cc617">
 

The error status:
1. Input should have red border
2. The page content should change the opacity to some low value (say 0.2) to indicate that it's not valid any more or disappear (the former is preferred though).

**Comment by krystian50** [comment]
Basic validation is added. Let me include proper styling as described in this issue.

**Comment by krystian50** [comment]
I changed native number input to npm library. It has a bit better UX https://www.npmjs.com/package/react-number-format

**Comment by tomusdrw** [comment]
Re-opening since #184 was broken and was reverted. Possibly fixed in #187

**Comment by krystian50** [comment]
Fixed and merged. Btw I fixed the width issue you posted on the screenshot.
