### ISSUE TITLE
Edit memory cell

### ISSUE THREAD

**Issue by piotrzwolinski** [FluffyLabs/pvm-debugger#24]
User should have the possibility to change value of specific cell in memory.

Editing:
- [ ] show input frame on hover
- [ ] click -> edit cell value (incl. validation, max values for hex / dec mode)
- [ ] tab -> change value and move to next cell
- [ ] esc - cancel editing

![Image](https://github.com/user-attachments/assets/5bb08bf9-d8b4-4320-8610-9ee0f7a47c66)

**Comment by tomusdrw** [comment]
I think it's not a goal for now. I'd focus on just reading/displaying the PVM data, not altering.

**Comment by tomusdrw** [comment]
not planned
