### ISSUE TITLE
Create instruction glossary database

### ISSUE THREAD

**Issue by piotrzwolinski** [FluffyLabs/pvm-debugger#32]
Prepare a clean dictionary for all instructions.

https://github.com/FluffyLabs/typeberry-toolkit/blob/main/src/utils/instructionsKnowledgeBase.ts

**Comment by tomusdrw** [comment]
I'd also be grateful for instruction number somewhere. It would also be cool to search by opcode number (dec/hex)

**Comment by tomusdrw** [comment]
I guess it's done now.
