### ISSUE TITLE
Load program

### ISSUE THREAD

**Issue by piotrzwolinski** [FluffyLabs/pvm-debugger#64]
**Load button**

![Image](https://github.com/user-attachments/assets/b0c71645-47bd-46bf-9760-7f4dfc002972)

**1. From file**

URL: https://github.com/w3f/jamtestvectors/pull/3/files#diff-4faad966a03de9e579ed189eebceaf870983ec407fc919253c5d997462c09f51

![Image](https://github.com/user-attachments/assets/e197e957-4913-4afa-aee1-781c2bf9b4da)

**2. Examples**

![Image](https://github.com/user-attachments/assets/c0d93297-2bdc-4d4b-b04c-531882fa8d7d)

**3. Bytecode**

![Image](https://github.com/user-attachments/assets/001f1bed-99d5-4bb0-bcba-bee86f6e2fdc)

**Comment by tomusdrw** [comment]
Done
