### ISSUE TITLE
Initial version of the debugger

### ISSUE THREAD

**Issue by piotrzwolinski** [FluffyLabs/pvm-debugger#7]
Basic functions of the debugger.

- [ ] The app should use the PVM / debugger API uploaded / referenced by the user
- [ ] "Play" button -> step by step execution of the next operation
- [ ] "Run" button -> run the program to the end 
- [ ] "Restart" button -> reinitiate the state and wait for user's action to play or run the program
- [ ]  update the state (initially the registers, program counter, status) and refresh the values in the UI after step / program execution

**Comment by tomusdrw** [comment]
Done.
